### ISSUE TITLE
Разобраться с библиотекой aiomoex

### ISSUE THREAD

**Issue by vktrbr** [nueramic/stock-bot#2]
## Понять как грузить данные из aiomoex
Будем, если все хорошо сложиться пользоваться библиотекой https://pypi.org/project/aiomoex/2.0.0/ https://github.com/WLM1ke/aiomoex

- [x] Нужно научиться грузить данные из MOEX с помощью этой библиотеки о нескольких тикерах, за часовые, минутные, дневные периоды. 
- [x] Понять, какие ассинхронные возможности дает данная библиотека. 

## Написать супер простые примеры 
- [x] Написать юпитер ноутбук с примерами использования этой библиотеки. Каждый пример должен быть с описанием и показывать полезный для нас функционал пока в рамках торговли одной бумагой.  

29-10-2022

**Comment by gstaranenko** [comment]
Ссылка на документацию: https://wlm1ke.github.io/aiomoex/build/html/index.html

**Comment by gstaranenko** [comment]
### Статус: 
Написаны функции для работы с тикером одной акции на примере Сбера. 

### Смысл реализованных функций:
0. Получить все возможные котировки акций
1. Получить период торгов конкретной акцией
2. Получить **дневные** значения цен по одному тикеру
    2.1.  в указанном режиме торгов
    2.2.  во всех режимах торгов
3. Получить значения цен по одному тикеру **за выбранный интервал**
    3.1.  в указанном режиме торгов
    3.2.  во всех режимах торгов

_Параметры интервалов:_
- 1 - 1 минута
- 10 - 10 минут
- 60 - 1 час
- 24 - 1 день
- 7 - 1 неделя
- 31 - 1 месяц
- 4 - 1 квартал

### Вывод: 
Библиотека подходит под наши потребности, единственный минус, который обнаружила - при выгрузке котировок с минутным интервалом в 12:50 последнее выгруженное значение было за период 12:34:00 до 12:34:59 - то есть с задержкой 15 минут
Все примеры были реализованы с использованием ассинхронных функций. Суть ассинхронного подхода - более быстрая выгрузка данных и более высокая скорость работы функций. Больше плюсов пока не обнаружено

**Comment by gstaranenko** [comment]
>  Нужно научиться грузить данные из MOEX с помощью этой библиотеки о нескольких тикерах, за часовые, минутные, дневные периоды.

О нескольких тикерах одновременно пока грузить не знаю как
